### ISSUE TITLE
unresolved dependency when try to get gearpump in sbt

### ISSUE THREAD

**Issue by Renkai** [gearpump/gearpump.github.io#16]
my build.sbt

```
name := "try-gearpump"

version := "1.0"

scalaVersion := "2.11.7"

val gearpumpVersion = "0.6.0"

resolvers ++= Seq(
  "patriknw at bintray" at "http://dl.bintray.com/patriknw/maven",
  "maven-repo" at "http://repo.maven.apache.org/maven2",
  "maven1-repo" at "http://repo1.maven.org/maven2",
  "maven2-repo" at "http://mvnrepository.com/artifact",
  "sonatype" at "https://oss.sonatype.org/content/repositories/releases",
  "bintray/non" at "http://dl.bintray.com/non/maven",
  "cloudera" at "https://repository.cloudera.com/artifactory/cloudera-repos",
  "clockfly" at "http://dl.bintray.com/clockfly/maven",
  "vincent" at "http://dl.bintray.com/fvunicorn/maven",
  "clojars" at "http://clojars.org/repo"
)

libraryDependencies ++= Seq(
  "com.github.intel-hadoop" %% "gearpump-core" % gearpumpVersion,
  "com.github.intel-hadoop" %% "gearpump-streaming" % gearpumpVersion
)
```

stack trace

```
[info] Loading global plugins from /Users/renkai/.sbt/0.13/plugins
[info] Updating {file:/Users/renkai/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/renkai/try-gearpump/project
[info] Set current project to try-gearpump (in build file:/Users/renkai/try-gearpump/)
[info] Updating {file:/Users/renkai/try-gearpump/}try-gearpump...
[info] Resolving com.github.intel-hadoop#gearpump-core_2.11;0.6.0 ...
[warn]  module not found: com.github.intel-hadoop#gearpump-core_2.11;0.6.0
[warn] ==== local: tried
[warn]   /Users/renkai/.ivy2/local/com.github.intel-hadoop/gearpump-core_2.11/0.6.0/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== patriknw at bintray: tried
[warn]   http://dl.bintray.com/patriknw/maven/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== maven-repo: tried
[warn]   http://repo.maven.apache.org/maven2/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== maven1-repo: tried
[warn]   http://repo1.maven.org/maven2/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== maven2-repo: tried
[warn]   http://mvnrepository.com/artifact/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== sonatype: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== bintray/non: tried
[warn]   http://dl.bintray.com/non/maven/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== cloudera: tried
[warn]   https://repository.cloudera.com/artifactory/cloudera-repos/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== clockfly: tried
[warn]   http://dl.bintray.com/clockfly/maven/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== vincent: tried
[warn]   http://dl.bintray.com/fvunicorn/maven/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[warn] ==== clojars: tried
[warn]   http://clojars.org/repo/com/github/intel-hadoop/gearpump-core_2.11/0.6.0/gearpump-core_2.11-0.6.0.pom
[info] Resolving com.github.intel-hadoop#gearpump-streaming_2.11;0.6.0 ...
[warn]  module not found: com.github.intel-hadoop#gearpump-streaming_2.11;0.6.0
[warn] ==== local: tried
[warn]   /Users/renkai/.ivy2/local/com.github.intel-hadoop/gearpump-streaming_2.11/0.6.0/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== patriknw at bintray: tried
[warn]   http://dl.bintray.com/patriknw/maven/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== maven-repo: tried
[warn]   http://repo.maven.apache.org/maven2/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== maven1-repo: tried
[warn]   http://repo1.maven.org/maven2/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== maven2-repo: tried
[warn]   http://mvnrepository.com/artifact/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== sonatype: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== bintray/non: tried
[warn]   http://dl.bintray.com/non/maven/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== cloudera: tried
[warn]   https://repository.cloudera.com/artifactory/cloudera-repos/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== clockfly: tried
[warn]   http://dl.bintray.com/clockfly/maven/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== vincent: tried
[warn]   http://dl.bintray.com/fvunicorn/maven/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[warn] ==== clojars: tried
[warn]   http://clojars.org/repo/com/github/intel-hadoop/gearpump-streaming_2.11/0.6.0/gearpump-streaming_2.11-0.6.0.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.intel-hadoop#gearpump-core_2.11;0.6.0: not found
[warn]  :: com.github.intel-hadoop#gearpump-streaming_2.11;0.6.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      com.github.intel-hadoop:gearpump-core_2.11:0.6.0 (/Users/renkai/try-gearpump/build.sbt#L22-26)
[warn]        +- default:try-gearpump_2.11:1.0
[warn]      com.github.intel-hadoop:gearpump-streaming_2.11:0.6.0 (/Users/renkai/try-gearpump/build.sbt#L22-26)
[warn]        +- default:try-gearpump_2.11:1.0
sbt.ResolveException: unresolved dependency: com.github.intel-hadoop#gearpump-core_2.11;0.6.0: not found
unresolved dependency: com.github.intel-hadoop#gearpump-streaming_2.11;0.6.0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.intel-hadoop#gearpump-core_2.11;0.6.0: not found
[error] unresolved dependency: com.github.intel-hadoop#gearpump-streaming_2.11;0.6.0: not found
[error] Total time: 20 s, completed 2015-9-8 20:11:07
```

**Comment by huafengw** [comment]
We are encountering some release problems, for a quick fix, you can try version `0.6.2-SNAPSHOT` which needs to add a resolver at`https://oss.sonatype.org/content/repositories/snapshots`

**Comment by manuzhang** [comment]
@Renkai We've successfully published 0.6.1.4. please try it out.

**Comment by clockfly** [comment]
document and download link updated on gearpump.io

**Comment by karol-brejna-i** [comment]
Could we have .tar.gz published also? It seems that zip doesn't store permission.
Hard to use it on *nix. Not a big issue, though...

**Comment by manuzhang** [comment]
You may open an issue at https://github.com/gearpump/gearpump/issues
